/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 15/01/2018 07:40:19
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            40000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            8000000
#define MX_HSE_VALUE                            8000000
#define MX_PLLCLKFreq_Value                     72000000
#define MX_SYSCLKFreq_VALUE                     72000000
#define MX_HCLKFreq_Value                       72000000
#define MX_HSIPLLFreq_Value                     4000000
#define MX_HSEPLLFreq_Value                     8000000
#define MX_MCOFreq_Value                        72000000
#define MX_CortexFreq_Value                     72000000
#define MX_AHBFreq_Value                        72000000
#define MX_APB1Freq_Value                       36000000
#define MX_APB2Freq_Value                       72000000
#define MX_APB1TimFreq_Value                    72000000
#define MX_APB2TimFreq_Value                    72000000
#define MX_I2C1Freq_Value                       8000000
#define MX_I2C2Freq_Value                       8000000
#define MX_USART1Freq_Value                     72000000
#define MX_USART2Freq_Value                     36000000
#define MX_USART3Freq_Value                     36000000
#define MX_RTCFreq_Value                        40000
#define MX_RTCHSEDivFreq_Value                  250000
#define MX_USBFreq_Value                        72000000
#define MX_WatchDogFreq_Value                   40000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PE11 */
#define MX_PE11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE11_Pin                             PE11
#define MX_PE11_GPIOx                           GPIOE
#define MX_PE11_PinState                        GPIO_PIN_RESET
#define MX_PE11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE11_GPIO_Pin                        GPIO_PIN_11
#define MX_PE11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE10 */
#define MX_PE10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE10_Pin                             PE10
#define MX_PE10_GPIOx                           GPIOE
#define MX_PE10_PinState                        GPIO_PIN_RESET
#define MX_PE10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE10_GPIO_Pin                        GPIO_PIN_10
#define MX_PE10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE8 */
#define MX_PE8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE8_Pin                              PE8
#define MX_PE8_GPIOx                            GPIOE
#define MX_PE8_PinState                         GPIO_PIN_RESET
#define MX_PE8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE8_GPIO_Pin                         GPIO_PIN_8
#define MX_PE8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE13 */
#define MX_PE13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE13_Pin                             PE13
#define MX_PE13_GPIOx                           GPIOE
#define MX_PE13_PinState                        GPIO_PIN_RESET
#define MX_PE13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE13_GPIO_Pin                        GPIO_PIN_13
#define MX_PE13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE12 */
#define MX_PE12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE12_Pin                             PE12
#define MX_PE12_GPIOx                           GPIOE
#define MX_PE12_PinState                        GPIO_PIN_RESET
#define MX_PE12_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE12_GPIO_Pin                        GPIO_PIN_12
#define MX_PE12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE9 */
#define MX_PE9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE9_Pin                              PE9
#define MX_PE9_GPIOx                            GPIOE
#define MX_PE9_PinState                         GPIO_PIN_RESET
#define MX_PE9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE9_GPIO_Pin                         GPIO_PIN_9
#define MX_PE9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE15 */
#define MX_PE15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE15_Pin                             PE15
#define MX_PE15_GPIOx                           GPIOE
#define MX_PE15_PinState                        GPIO_PIN_RESET
#define MX_PE15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE15_GPIO_Pin                        GPIO_PIN_15
#define MX_PE15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE14 */
#define MX_PE14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE14_Pin                             PE14
#define MX_PE14_GPIOx                           GPIOE
#define MX_PE14_PinState                        GPIO_PIN_RESET
#define MX_PE14_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE14_GPIO_Pin                        GPIO_PIN_14
#define MX_PE14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA0 */
#define MX_PA0_Pin                              PA0
#define MX_PA0_GPIOx                            GPIOA
#define MX_PA0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA0_GPIO_Pin                         GPIO_PIN_0
#define MX_PA0_GPIO_Mode                        GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */
